GET http://localhost:3000/categories
// Description: Retrieve all categories

GET http://localhost:3000/categories/29c7eb85-0bbc-46af-9d96-ccb7c28bf344
// Description: Retrieve a specific category by ID